# Generated by Django 2.2.3 on 2020-01-15 11:59

import accounts.models
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Archive'), (3, 'Draft')], db_index=True, default=6, verbose_name='Status Data')),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=40, unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Nama Depan')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Nama Belakang')),
                ('tempat_lahir', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telepon')),
                ('alamat', models.CharField(max_length=255)),
                ('lt', models.CharField(blank=True, max_length=50, null=True, verbose_name='lt')),
                ('lg', models.CharField(blank=True, max_length=50, null=True, verbose_name='lg')),
                ('foto', accounts.models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.PathAndRename('profiles/'))),
                ('sv', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Akun',
                'verbose_name_plural': 'Akun',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountHistoryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Riwayat Aksi Pengguna',
                'verbose_name_plural': 'Riwayat Aksi Pengguna',
            },
        ),
        migrations.CreateModel(
            name='NomorIdentitasPengguna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nomor Identitas Pengguna',
                'verbose_name_plural': 'Nomor Identitas Pengguna',
            },
        ),
    ]
